name: Build and Deploy React App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TATA_PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TATA_PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.TATA_PROD_AWS_REGION }}

      - name: Set Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Deploy to AWS
        run: |
          export CI=''
          npm install
          npm run build
          aws s3 sync build/ s3://designhubz-widget-new-deployment/react-widget-example --acl public-read

      - name: Invalidate Cloudfront distribution
        run: aws cloudfront create-invalidation --distribution-id E186U475VBQBQ4 --paths "/*"


